linear.3.1 <- glm(formula = stargazers_count ~ ratio + age, data = contributions )
linear.3.2 <- glm(formula = stargazers_count ~ ratio + age + lang_, data = contributions )
linear.3.3 <- glm(formula = stargazers_count ~ ratio + age + firm_, data = contributions )
linear.3.4 <- glm(formula = stargazers_count ~ ratio + age + firm_ + lang_, data = contributions )
linear.3.5 <- glm(formula = subscribers_count ~ ratio + age, data = contributions )
linear.3.6 <- glm(formula = subscribers_count ~ ratio + age + lang_, data = contributions )
linear.3.7 <- glm(formula = subscribers_count ~ ratio + age + firm_, data = contributions )
linear.3.8 <- glm(formula = subscribers_count ~ ratio + age + firm_ + lang_, data = contributions )
linear.3.9 <- glm(formula = forks_count ~ ratio + age , data = contributions)
linear.3.10 <- glm(formula = forks_count ~ ratio + age + lang_, data = contributions)
linear.3.11 <- glm(formula = forks_count ~ ratio + age + firm_, data = contributions)
linear.3.12 <- glm(formula = forks_count ~ ratio + age + firm_ + lang_, data = contributions)

linear.3.13 <- glm(formula = all_issues_count ~ ratio + age , data = contributions)
linear.3.14 <- glm(formula = all_issues_count ~ ratio + age + lang_, data = contributions)
linear.3.15 <- glm(formula = all_issues_count ~ ratio + age + firm_, data = contributions)
linear.3.16 <- glm(formula = all_issues_count ~ ratio + age + firm_ + lang_, data = contributions)
linear.3.17 <- glm(formula = contributors_count ~ ratio + age , data = contributions)
linear.3.18 <- glm(formula = contributors_count ~ ratio + age + lang_, data = contributions)
linear.3.19 <- glm(formula = contributors_count ~ ratio + age + firm_, data = contributions)
linear.3.20 <- glm(formula = contributors_count ~ ratio + age + firm_ + lang_, data = contributions)
linear.3.21 <- glm(formula = top_repo ~ ratio + age , family=binomial(link='logit'), data = contributions )
linear.3.22 <- glm(formula = top_repo ~ ratio + age + lang_, family=binomial(link='logit'), data = contributions )
linear.3.23 <- glm(formula = top_repo ~ ratio + age + firm_, family=binomial(link='logit'), data = contributions )
linear.3.24 <- glm(formula = top_repo ~ ratio + age + firm_ + lang_, family=binomial(link='logit'), data = contributions )

mixedeffect.3.25 <- lmer(formula = stargazers_count ~ ratio + age + (1 | organization_name), data = contributions)
mixedeffect.3.26 <- lmer(formula = subscribers_count ~ ratio + age + (1 | organization_name), data = contributions)
mixedeffect.3.27 <- lmer(formula = forks_count ~ ratio + age + (1 | organization_name), data = contributions)
mixedeffect.3.28 <- lmer(formula = all_issues_count ~ ratio + age + (1 | organization_name), data = contributions)
mixedeffect.3.29 <- lmer(formula = contributors_count ~ ratio + age + (1 | organization_name), data = contributions)
mixedeffect.3.30 <- lmer(formula = top_repo ~ ratio + age + (1 | organization_name), family=binomial(link='logit'), data = contributions)

mixedeffect.3.31 <- lmer(formula = stargazers_count ~ ratio + age + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.32 <- lmer(formula = subscribers_count ~ ratio + age + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.33 <- lmer(formula = forks_count ~ ratio + age + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.34 <- lmer(formula = all_issues_count ~ ratio + age + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.35 <- lmer(formula = contributors_count ~ ratio + age + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.36 <- glmer(formula = top_repo ~ ratio + age + (1 | organization_name) + (1 | language), family=binomial(link='logit'), data = contributions)

mixedeffect.3.37 <- lmer(formula = ratio ~ stargazers_count + (1 | organization_name), data = contributions)
mixedeffect.3.38 <- lmer(formula = ratio ~ subscribers_count + (1 | organization_name), data = contributions)
mixedeffect.3.39 <- lmer(formula = ratio ~ forks_count + (1 | organization_name), data = contributions)
mixedeffect.3.40 <- lmer(formula = ratio ~ all_issues_count + (1 | organization_name), data = contributions)
mixedeffect.3.41 <- lmer(formula = ratio ~ contributors_count + (1 | organization_name), data = contributions)
mixedeffect.3.42 <- lmer(formula = ratio ~ top_repo + (1 | organization_name), data = contributions)

mixedeffect.3.43 <- lmer(formula = ratio ~ stargazers_count + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.44 <- lmer(formula = ratio ~ subscribers_count + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.45 <- lmer(formula = ratio ~ forks_count + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.46 <- lmer(formula = ratio ~ all_issues_count + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.47 <- lmer(formula = ratio ~ contributors_count + (1 | organization_name) + (1 | language), data = contributions)
mixedeffect.3.48 <- lmer(formula = ratio ~ top_repo + (1 | organization_name) + (1 | language), data = contributions)
