linear.1.2.1 <- lm(formula = issues_count_by_external_developer ~ issues_count_by_firm_employed_developer, data = issues)
linear.1.2.2 <- lm(formula = issues_count_by_firm_employed_developer ~ issues_count_by_external_developer, data = issues)
linear.1.2.3 <- lm(formula = issues_count_by_external_developer ~ issues_count_by_firm_employed_developer, data = issues[issues$is_top_project == TRUE,])
linear.1.2.4 <- lm(formula = issues_count_by_firm_employed_developer ~ issues_count_by_external_developer, data = issues[issues$is_top_project == TRUE,])
linear.1.2.5 <- lm(formula = issues_count_by_external_developer ~ issues_count_by_firm_employed_developer, data = issues[issues$is_top_project == FALSE,])
linear.1.2.6 <- lm(formula = issues_count_by_firm_employed_developer ~ issues_count_by_external_developer, data = issues[issues$is_top_project == FALSE,])
linear.1.2.7 <- lm(formula = issues_count_by_external_developer ~ issues_count_by_firm_employed_developer, data = issues[issues$is_top_project == TRUE & issues$age >= 365,])
linear.1.2.8 <- lm(formula = issues_count_by_firm_employed_developer ~ issues_count_by_external_developer, data = issues[issues$is_top_project == TRUE & issues$age >= 365,])
linear.1.2.9 <- lm(formula = issues_count_by_external_developer ~ issues_count_by_firm_employed_developer, data = issues[issues$is_top_project == FALSE & issues$age >= 365,])
linear.1.2.10 <- lm(formula = issues_count_by_firm_employed_developer ~ issues_count_by_external_developer, data = issues[issues$is_top_project == FALSE & issues$age >= 365,])
linear.1.2.11 <- lm(formula = issues_count_by_external_developer ~ issues_count_by_firm_employed_developer, data = issues[issues$is_top_project == TRUE & issues$age < 365,])
linear.1.2.12 <- lm(formula = issues_count_by_firm_employed_developer ~ issues_count_by_external_developer, data = issues[issues$is_top_project == TRUE & issues$age < 365,])
linear.1.2.13 <- lm(formula = issues_count_by_external_developer ~ issues_count_by_firm_employed_developer, data = issues[issues$is_top_project == FALSE & issues$age < 365,])
linear.1.2.14 <- lm(formula = issues_count_by_firm_employed_developer ~ issues_count_by_external_developer, data = issues[issues$is_top_project == FALSE & issues$age < 365,])
