linear.1.1.1 <- lm(formula = `ext. commits` ~ `int. commits`, data = codeContributions)
linear.1.1.2 <- lm(formula = `int. commits` ~ `ext. commits`, data = codeContributions)
linear.1.1.3 <- lm(formula = `ext. commits` ~ `int. commits`, data = codeContributions[codeContributions$is_top_project == TRUE,])
linear.1.1.4 <- lm(formula = `int. commits` ~ `ext. commits`, data = codeContributions[codeContributions$is_top_project == TRUE,])
linear.1.1.5 <- lm(formula = `ext. commits` ~ `int. commits`, data = codeContributions[codeContributions$is_top_project == FALSE,])
linear.1.1.6 <- lm(formula = `int. commits` ~ `ext. commits`, data = codeContributions[codeContributions$is_top_project == FALSE,])
linear.1.1.7 <- lm(formula = `ext. commits` ~ `int. commits`, data = codeContributions[codeContributions$is_top_project == TRUE & codeContributions$age >= 365,])
linear.1.1.8 <- lm(formula = `int. commits` ~ `ext. commits`, data = codeContributions[codeContributions$is_top_project == TRUE & codeContributions$age >= 365,])
linear.1.1.9 <- lm(formula = `ext. commits` ~ `int. commits`, data = codeContributions[codeContributions$is_top_project == FALSE & codeContributions$age >= 365,])
linear.1.1.10 <- lm(formula = `int. commits` ~ `ext. commits`, data = codeContributions[codeContributions$is_top_project == FALSE & codeContributions$age >= 365,])
linear.1.1.11 <- lm(formula = `ext. commits` ~ `int. commits`, data = codeContributions[codeContributions$is_top_project == TRUE & codeContributions$age < 365,])
linear.1.1.12 <- lm(formula = `int. commits` ~ `ext. commits`, data = codeContributions[codeContributions$is_top_project == TRUE & codeContributions$age < 365,])
linear.1.1.13 <- lm(formula = `ext. commits` ~ `int. commits`, data = codeContributions[codeContributions$is_top_project == FALSE & codeContributions$age < 365,])
linear.1.1.14 <- lm(formula = `int. commits` ~ `ext. commits`, data = codeContributions[codeContributions$is_top_project == FALSE & codeContributions$age < 365,])
