contribs # all projects
linear.1 <- lm(formula = `ext. commits` ~ `int. commits`, data = contribs)
linear.2 <- lm(formula = `int. commits` ~ `ext. commits`, data = contribs)
linear.3 <- lm(formula = `ext. commits` ~ `int. commits`, data = contribs[contribs$is_top_project == T,])
linear.4 <- lm(formula = `int. commits` ~ `ext. commits`, data = contribs[contribs$is_top_project == T,])
linear.5 <- lm(formula = `ext. commits` ~ `int. commits`, data = contribs[contribs$is_top_project == F,])
linear.6 <- lm(formula = `int. commits` ~ `ext. commits`, data = contribs[contribs$is_top_project == F,])
linear.7 <- lm(formula = `ext. commits` ~ `int. commits`, data = contribs[contribs$is_top_project == T & contribs$age >= 365,])
linear.8 <- lm(formula = `int. commits` ~ `ext. commits`, data = contribs[contribs$is_top_project == T & contribs$age >= 365,])
linear.9 <- lm(formula = `ext. commits` ~ `int. commits`, data = contribs[contribs$is_top_project == F & contribs$age >= 365,])
linear.10 <- lm(formula = `int. commits` ~ `ext. commits`, data = contribs[contribs$is_top_project == F & contribs$age >= 365,])
linear.11 <- lm(formula = `ext. commits` ~ `int. commits`, data = contribs[contribs$is_top_project == T & contribs$age < 365,])
linear.12 <- lm(formula = `int. commits` ~ `ext. commits`, data = contribs[contribs$is_top_project == T & contribs$age < 365,])
linear.13 <- lm(formula = `ext. commits` ~ `int. commits`, data = contribs[contribs$is_top_project == F & contribs$age < 365,])
linear.14 <- lm(formula = `int. commits` ~ `ext. commits`, data = contribs[contribs$is_top_project == F & contribs$age < 365,])
